name: CI/CD

on:
    push:
        branches: master
    pull_request_target:
        branches: master
        types: [opened, synchronize, reopened]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
            - name: Setup Node Environment
              uses: actions/setup-node@v4
              with:
                  node-version: "14.x"
                  registry-url: https://npm.pkg.github.com/
            - name: Install packages
              run: npm install
            - name: Build and Test
              run: npm run build && npm run test

            - name: Generate Version
              if: github.event_name == 'push'
              uses: go-semantic-release/action@v1
              id: semanticRelease
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  update-file: package.json
                  changelog-generator-opt: "emojis=true"
                  force-bump-patch-version: true
            - name: Publish Package
              if: steps.semanticRelease.outputs.version != ''
              run: |
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
